### ISSUE TITLE
Possibly rename project to `Unity-WebVR-Sample-Assets`?

### ISSUE THREAD

**Issue by cvan** [gtk2k/Unity-WebVR-Test-Assets#10]

**Comment by gtk2k** [comment]
I agree with your opinion.
I have never experienced rename is foked repository.
Is there no problem if the renamed?

**Comment by cvan** [comment]
> Is there no problem if the renamed?

There's no problem. GitHub adds redirects. So when someone loads https://github.com/gtk2k/Unity-WebVR-Test-Assets/, the user will be redirected to https://github.com/gtk2k/Unity-WebVR-Sample-Assets/ 😄

**Comment by gtk2k** [comment]
Thanks answer!!
OK! 
Project name renamed !
