### ISSUE TITLE
Remove three.js dependency

### ISSUE THREAD

**Issue by caseyyee** [gtk2k/Unity-WebVR-Test-Assets#23]
Only used for some unity conversion.    Not required otherwise.

**Comment by cvan** [comment]
I did this in https://github.com/gtk2k/Unity-WebVR-Assets/issues/11 but then we have more `THREE` math being used. is there a better smaller lib we can use? http://glmatrix.net/?

**Comment by caseyyee** [comment]
Oh, didn't notice that.  I think #11 is fine.  glmatrix doesn't appear to have Quaternion -> Euler anyways.    As long as entire three isn't being included.

**Comment by cvan** [comment]
you can reopen - or @gtk2k needs to open #11.

**Comment by cvan** [comment]
yeah, I tried but there were too many dependencies in `THREE.Euler`, and then I was inheriting all of `THREE.Math`, and then I realised this would be impossible to update/diff against. any better library to handle the math?
